#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.10
# In conjunction with Tcl version 8.6
#    Jan 22, 2018 11:41:00 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import MainWindow_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    MainWindow_support.set_Tk_var()
    top = MirageTankGoGUI (root)
    MainWindow_support.init(root, top)
    root.mainloop()

w = None
def create_MirageTankGoGUI(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    MainWindow_support.set_Tk_var()
    top = MirageTankGoGUI (w)
    MainWindow_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_MirageTankGoGUI():
    global w
    w.destroy()
    w = None


class MirageTankGoGUI:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 

        top.geometry("807x719+381+180")
        top.title("MirageTankGoGUI")
        top.configure(highlightcolor="black")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.02, rely=0.26, relheight=0.72, relwidth=0.96)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(width=775)

        self.showWhite = Label(self.Frame1)
        self.showWhite.place(relx=0.03, rely=0.02, height=485, width=340)
        self.showWhite.configure(activebackground="#f9f9f9")
        self.showWhite.configure(background="#ffffff")
        self.showWhite.configure(text='''白底效果''')

        self.showBlack = Label(self.Frame1)
        self.showBlack.place(relx=0.53, rely=0.02, height=485, width=340)
        self.showBlack.configure(activebackground="#f9f9f9")
        self.showBlack.configure(background="#000000")
        self.showBlack.configure(foreground="#ffffff")
        self.showBlack.configure(text='''黑底效果''')

        self.Frame2 = Frame(top)
        self.Frame2.place(relx=0.52, rely=0.01, relheight=0.24, relwidth=0.46)
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(width=375)

        self.cenableChess = Checkbutton(self.Frame2)
        self.cenableChess.place(relx=0.01, rely=0.07, relheight=0.15
                , relwidth=0.28)
        self.cenableChess.configure(activebackground="#f9f9f9")
        self.cenableChess.configure(command=MainWindow_support.switchGray)
        self.cenableChess.configure(justify=LEFT)
        self.cenableChess.configure(text='''启用棋盘格''')
        self.cenableChess.configure(variable=MainWindow_support.enableChess)

        self.ccolorfulCar = Checkbutton(self.Frame2)
        self.ccolorfulCar.place(relx=0.01, rely=0.3, relheight=0.15
                , relwidth=0.24)
        self.ccolorfulCar.configure(activebackground="#f9f9f9")
        self.ccolorfulCar.configure(command=MainWindow_support.switchColor)
        self.ccolorfulCar.configure(justify=LEFT)
        self.ccolorfulCar.configure(text='''发彩色车''')
        self.ccolorfulCar.configure(variable=MainWindow_support.colorfulCar)

        self.Label11 = Label(self.Frame2)
        self.Label11.place(relx=0.03, rely=0.53, height=24, width=68)
        self.Label11.configure(activebackground="#f9f9f9")
        self.Label11.configure(text='''白底色彩:''')

        self.Label12 = Label(self.Frame2)
        self.Label12.place(relx=0.03, rely=0.75, height=24, width=68)
        self.Label12.configure(activebackground="#f9f9f9")
        self.Label12.configure(text='''黑底色彩:''')

        self.swhiteColor = Spinbox(self.Frame2, from_=0.0, to=1.0)
        self.swhiteColor.place(relx=0.24, rely=0.53, relheight=0.15
                , relwidth=0.2)
        self.swhiteColor.configure(activebackground="#f9f9f9")
        self.swhiteColor.configure(background="white")
        self.swhiteColor.configure(increment="0.01")
        self.swhiteColor.configure(justify=RIGHT)
        self.swhiteColor.configure(selectbackground="#c4c4c4")
        self.swhiteColor.configure(textvariable=MainWindow_support.whiteColor)
        self.swhiteColor.configure(to="1.0")

        self.sblackColor = Spinbox(self.Frame2, from_=0.0, to=1.0)
        self.sblackColor.place(relx=0.24, rely=0.75, relheight=0.15
                , relwidth=0.2)
        self.sblackColor.configure(activebackground="#f9f9f9")
        self.sblackColor.configure(background="white")
        self.sblackColor.configure(increment="0.01")
        self.sblackColor.configure(justify=RIGHT)
        self.sblackColor.configure(selectbackground="#c4c4c4")
        self.sblackColor.configure(textvariable=MainWindow_support.blackColor)
        self.sblackColor.configure(to="1.0")

        self.Label13 = Label(self.Frame2)
        self.Label13.place(relx=0.56, rely=0.07, height=24, width=68)
        self.Label13.configure(activebackground="#f9f9f9")
        self.Label13.configure(text='''白底缩放:''')

        self.Label8 = Label(self.Frame2)
        self.Label8.place(relx=0.56, rely=0.3, height=24, width=68)
        self.Label8.configure(activebackground="#f9f9f9")
        self.Label8.configure(text='''黑底缩放:''')

        self.Label10 = Label(self.Frame2)
        self.Label10.place(relx=0.56, rely=0.53, height=24, width=68)
        self.Label10.configure(activebackground="#f9f9f9")
        self.Label10.configure(text='''白底亮度:''')

        self.Label9 = Label(self.Frame2)
        self.Label9.place(relx=0.56, rely=0.75, height=24, width=68)
        self.Label9.configure(activebackground="#f9f9f9")
        self.Label9.configure(text='''黑底亮度:''')

        self.swhiteScale = Spinbox(self.Frame2, from_=0.01, to=1.0)
        self.swhiteScale.place(relx=0.77, rely=0.07, relheight=0.15
                , relwidth=0.2)
        self.swhiteScale.configure(activebackground="#f9f9f9")
        self.swhiteScale.configure(background="white")
        self.swhiteScale.configure(from_="0.01")
        self.swhiteScale.configure(increment="0.01")
        self.swhiteScale.configure(justify=RIGHT)
        self.swhiteScale.configure(selectbackground="#c4c4c4")
        self.swhiteScale.configure(textvariable=MainWindow_support.whiteScale)
        self.swhiteScale.configure(to="1.0")

        self.sblackScale = Spinbox(self.Frame2, from_=0.01, to=1.0)
        self.sblackScale.place(relx=0.77, rely=0.3, relheight=0.15, relwidth=0.2)

        self.sblackScale.configure(activebackground="#f9f9f9")
        self.sblackScale.configure(background="white")
        self.sblackScale.configure(from_="0.01")
        self.sblackScale.configure(increment="0.01")
        self.sblackScale.configure(justify=RIGHT)
        self.sblackScale.configure(selectbackground="#c4c4c4")
        self.sblackScale.configure(textvariable=MainWindow_support.blackScale)
        self.sblackScale.configure(to="1.0")

        self.swhiteLight = Spinbox(self.Frame2, from_=0.0, to=1.0)
        self.swhiteLight.place(relx=0.77, rely=0.53, relheight=0.15
                , relwidth=0.2)
        self.swhiteLight.configure(activebackground="#f9f9f9")
        self.swhiteLight.configure(background="white")
        self.swhiteLight.configure(increment="0.01")
        self.swhiteLight.configure(justify=RIGHT)
        self.swhiteLight.configure(selectbackground="#c4c4c4")
        self.swhiteLight.configure(textvariable=MainWindow_support.whiteLight)
        self.swhiteLight.configure(to="1.0")

        self.sblackLight = Spinbox(self.Frame2, from_=0.0, to=1.0)
        self.sblackLight.place(relx=0.77, rely=0.75, relheight=0.15
                , relwidth=0.2)
        self.sblackLight.configure(activebackground="#f9f9f9")
        self.sblackLight.configure(background="white")
        self.sblackLight.configure(increment="0.01")
        self.sblackLight.configure(justify=RIGHT)
        self.sblackLight.configure(selectbackground="#c4c4c4")
        self.sblackLight.configure(textvariable=MainWindow_support.blackLight)
        self.sblackLight.configure(to="1.0")

        self.Frame3 = Frame(top)
        self.Frame3.place(relx=0.02, rely=0.01, relheight=0.24, relwidth=0.49)
        self.Frame3.configure(relief=GROOVE)
        self.Frame3.configure(borderwidth="2")
        self.Frame3.configure(relief=GROOVE)
        self.Frame3.configure(width=395)

        self.Label1 = Label(self.Frame3)
        self.Label1.place(relx=0.05, rely=0.07, height=24, width=68)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(text='''白底图片:''')

        self.ewhiteImg = Entry(self.Frame3)
        self.ewhiteImg.place(relx=0.25, rely=0.07,height=26, relwidth=0.52)
        self.ewhiteImg.configure(background="white")
        self.ewhiteImg.configure(font="TkFixedFont")
        self.ewhiteImg.configure(selectbackground="#c4c4c4")
        self.ewhiteImg.configure(textvariable=MainWindow_support.whiteImg)

        self.eblackImg = Entry(self.Frame3)
        self.eblackImg.place(relx=0.25, rely=0.24,height=26, relwidth=0.52)
        self.eblackImg.configure(background="white")
        self.eblackImg.configure(font="TkFixedFont")
        self.eblackImg.configure(selectbackground="#c4c4c4")
        self.eblackImg.configure(textvariable=MainWindow_support.blackImg)

        self.eoutputImg = Entry(self.Frame3)
        self.eoutputImg.place(relx=0.25, rely=0.41,height=26, relwidth=0.52)
        self.eoutputImg.configure(background="white")
        self.eoutputImg.configure(font="TkFixedFont")
        self.eoutputImg.configure(selectbackground="#c4c4c4")
        self.eoutputImg.configure(textvariable=MainWindow_support.outputImg)

        self.bwhiteBrowse = Button(self.Frame3)
        self.bwhiteBrowse.place(relx=0.78, rely=0.07, height=26, width=72)
        self.bwhiteBrowse.configure(activebackground="#f9f9f9")
        self.bwhiteBrowse.configure(command=MainWindow_support.whiteBrowser)
        self.bwhiteBrowse.configure(text='''浏览..''')

        self.bblackBrowse = Button(self.Frame3)
        self.bblackBrowse.place(relx=0.78, rely=0.24, height=26, width=72)
        self.bblackBrowse.configure(activebackground="#f9f9f9")
        self.bblackBrowse.configure(command=MainWindow_support.blackBrowser)
        self.bblackBrowse.configure(text='''浏览..''')

        self.boutputBrowse = Button(self.Frame3)
        self.boutputBrowse.place(relx=0.78, rely=0.41, height=26, width=72)
        self.boutputBrowse.configure(activebackground="#f9f9f9")
        self.boutputBrowse.configure(command=MainWindow_support.outputBrowser)
        self.boutputBrowse.configure(text='''浏览..''')

        self.btryBuild = Button(self.Frame3)
        self.btryBuild.place(relx=0.05, rely=0.64, height=42, width=132)
        self.btryBuild.configure(activebackground="#f9f9f9")
        self.btryBuild.configure(command=MainWindow_support.tryBuild)
        self.btryBuild.configure(text='''试驾''')

        self.bstartBuild = Button(self.Frame3)
        self.bstartBuild.place(relx=0.61, rely=0.64, height=42, width=132)
        self.bstartBuild.configure(activebackground="#f9f9f9")
        self.bstartBuild.configure(command=MainWindow_support.startBuild)
        self.bstartBuild.configure(text='''开始发车!''')

        self.Label2 = Label(self.Frame3)
        self.Label2.place(relx=0.05, rely=0.24, height=24, width=68)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(text='''黑底图片:''')

        self.Label3 = Label(self.Frame3)
        self.Label3.place(relx=0.05, rely=0.41, height=24, width=68)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(text='''输出图片:''')

        self.menubar = Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.menubar.add_command(
                activebackground="#d8d8d8",
                activeforeground="#000000",
                background="#d9d9d9",
                command=MainWindow_support.mabout,
                font="TkMenuFont",
                foreground="#000000",
                label="关于")







if __name__ == '__main__':
    vp_start_gui()



