#! /usr/bin/env python
#
# Support module generated by PAGE version 4.10
# In conjunction with Tcl version 8.6
#    Jan 20, 2018 09:32:11 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *
    import tkinter.filedialog as filedialog
    import tkinter.messagebox as messagebox
    import MirageTankGo

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1


def hideFileBrowser():
    global w
    print('MainWindow_support.hideFileBrowser')
    filename = filedialog.askopenfilename(filetypes=[('任何图片', '.*')])
    w.hideFile.delete(0, END)
    w.hideFile.insert(0, filename)
    sys.stdout.flush()

def hostFileBrowser():
    global w
    print('MainWindow_support.hostFileBrowser')
    filename = filedialog.askopenfilename(filetypes=[('任何图片', '.*')])
    w.hostFile.delete(0, END)
    w.hostFile.insert(0, filename)
    sys.stdout.flush()

def outputFileBrowser():
    global w
    print('MainWindow_support.outputFileBrowser')
    filename = filedialog.asksaveasfilename(filetypes=[('png图片', '.png')])
    w.outputFile.delete(0, END)
    w.outputFile.insert(0, filename)
    sys.stdout.flush()

def startBuild():
    global w
    print('MainWindow_support.startBuild')
    hostFile = w.hostFile.get()
    hideFile = w.hideFile.get()
    ouputFile = w.outputFile.get()
    hideRatio = w.hideRatio.get()
    MirageTankGo.main(hostFile, hideFile, ouputFile, hideRatio)
    messagebox.showinfo(title='提示', message='转换成功!')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

# Placeholder to be replace by user definition of Custom.
Custom = Frame

if __name__ == '__main__':
    import MainWindow
    MainWindow.vp_start_gui()


