#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.10
# In conjunction with Tcl version 8.6
#    Jan 20, 2018 09:32:05 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import MainWindow_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = MirageTankGoGUI (root)
    MainWindow_support.init(root, top)
    root.mainloop()

w = None
def create_MirageTankGoGUI(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = MirageTankGoGUI (w)
    MainWindow_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_MirageTankGoGUI():
    global w
    w.destroy()
    w = None


class MirageTankGoGUI:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 

        top.geometry("367x224+700+400")
        top.title("MirageTankGoGUI")
        top.configure(highlightcolor="black")



        self.hostFile = Entry(top)
        self.hostFile.place(relx=0.27, rely=0.13,height=26, relwidth=0.43)
        self.hostFile.configure(background="white")
        self.hostFile.configure(font="TkFixedFont")
        self.hostFile.configure(selectbackground="#c4c4c4")

        self.Custom1 = MainWindow_support.Custom(top)
        self.Custom1.place(relx=0.44, rely=1.07, relheight=0.29, relwidth=0.23)

        self.hostBrowse = Button(top)
        self.hostBrowse.place(relx=0.71, rely=0.13, height=26, width=72)
        self.hostBrowse.configure(activebackground="#d9d9d9")
        self.hostBrowse.configure(command=MainWindow_support.hostFileBrowser)
        self.hostBrowse.configure(state=ACTIVE)
        self.hostBrowse.configure(text='''浏览..''')

        self.Label1 = Label(top)
        self.Label1.place(relx=0.08, rely=0.13, height=24, width=68)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(text='''宿主文件:''')

        self.Label2 = Label(top)
        self.Label2.place(relx=0.08, rely=0.27, height=24, width=72)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(text='''隐藏文件:''')

        self.hideFile = Entry(top)
        self.hideFile.place(relx=0.27, rely=0.27,height=26, relwidth=0.43)
        self.hideFile.configure(background="white")
        self.hideFile.configure(font="TkFixedFont")
        self.hideFile.configure(selectbackground="#c4c4c4")

        self.hideBrowse = Button(top)
        self.hideBrowse.place(relx=0.71, rely=0.27, height=26, width=72)
        self.hideBrowse.configure(activebackground="#d9d9d9")
        self.hideBrowse.configure(command=MainWindow_support.hideFileBrowser)
        self.hideBrowse.configure(text='''浏览..''')

        self.outputFile = Entry(top)
        self.outputFile.place(relx=0.27, rely=0.4,height=26, relwidth=0.43)
        self.outputFile.configure(background="white")
        self.outputFile.configure(font="TkFixedFont")
        self.outputFile.configure(selectbackground="#c4c4c4")

        self.outputBrowse = Button(top)
        self.outputBrowse.place(relx=0.71, rely=0.4, height=26, width=72)
        self.outputBrowse.configure(activebackground="#d9d9d9")
        self.outputBrowse.configure(command=MainWindow_support.outputFileBrowser)
        self.outputBrowse.configure(text='''浏览..''')

        self.Label3 = Label(top)
        self.Label3.place(relx=0.08, rely=0.4, height=24, width=68)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(text='''输出文件:''')

        self.hideRatio = Spinbox(top, from_=0.0, to=1.0)
        self.hideRatio.place(relx=0.27, rely=0.54, relheight=0.12, relwidth=0.43)

        self.hideRatio.configure(activebackground="#f9f9f9")
        self.hideRatio.configure(background="white")
        self.hideRatio.configure(increment="0.1")
        self.hideRatio.configure(justify=RIGHT)
        self.hideRatio.configure(selectbackground="#c4c4c4")
        self.hideRatio.configure(to="1.0")
        self.value_list = [0.3,]
        self.hideRatio.configure(values=self.value_list)

        self.Label4 = Label(top)
        self.Label4.place(relx=0.08, rely=0.54, height=24, width=68)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(text='''隐藏系数:''')

        self.start = Button(top)
        self.start.place(relx=0.22, rely=0.71, height=42, width=222)
        self.start.configure(activebackground="#d9d9d9")
        self.start.configure(command=MainWindow_support.startBuild)
        self.start.configure(text='''开始发车!''')






if __name__ == '__main__':
    vp_start_gui()



