#! /usr/bin/env python
#
# Support module generated by PAGE version 4.10
# In conjunction with Tcl version 8.6
#    Jan 22, 2018 12:13:14 AM
#    Jan 22, 2018 08:45:13 AM
#    Jan 22, 2018 09:10:39 AM
#    Jan 22, 2018 09:23:50 AM
#    Jan 22, 2018 08:51:51 PM
#    Jan 22, 2018 09:23:19 PM
#    Jan 22, 2018 09:45:46 PM
#    Jan 22, 2018 10:17:40 PM
#    Jan 22, 2018 11:28:01 PM
#    Aug 20, 2019 01:11:03 PM

from operator import methodcaller

import json

try:
    from Tkinter import *
except ImportError:
    from tkinter import *
    import tkinter.filedialog as filedialog
    import tkinter.messagebox as messagebox
    from PIL import Image
    from PIL import ImageTk

try:
    from MTCore import CMTCore as MTCore
except ImportError:
    from MTCore import MTCore

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

def set_Tk_var():
    global whiteImg
    whiteImg = StringVar()

    global blackImg
    blackImg = StringVar()

    global outputImg
    outputImg = StringVar()

    global blackLight
    blackLight = DoubleVar()

    global whiteLight
    whiteLight = DoubleVar()

    global whiteColor
    whiteColor = DoubleVar()

    global blackColor
    blackColor = DoubleVar()

    global blackScale
    blackScale = DoubleVar()

    global whiteScale
    whiteScale = DoubleVar()

    global enableChess
    enableChess = BooleanVar()

    global colorfulCar
    colorfulCar = BooleanVar()

    with open('options.json') as f:
        options = json.load(f)

    for option, value in options.items():
        globals()[option].set(value)



def bcolor():
    print('MainWindow_support.bcolor')
    tryBuild()
    sys.stdout.flush()

def blight():
    print('MainWindow_support.blight')
    tryBuild()
    sys.stdout.flush()

def bscale():
    print('MainWindow_support.bscale')
    tryBuild()
    sys.stdout.flush()

def wcolor():
    print('MainWindow_support.wcolor')
    tryBuild()
    sys.stdout.flush()

def wlight():
    print('MainWindow_support.wlight')
    tryBuild()
    sys.stdout.flush()

def wscale():
    print('MainWindow_support.wscale')
    tryBuild()
    sys.stdout.flush()

def switchColor():
    global w, colorfulCar
    print('MainWindow_support.switchColor')
    tryBuild()
    sys.stdout.flush()

def mabout():
    print('MainWindow_support.mabout')
    messagebox.showinfo(title='关于', message='MirageTankGo\n项目主页:\nhttps://github.com/YinTianliang/MirageTankGo')
    sys.stdout.flush()

def switchGray():
    global w, enableChess
    print('MainWindow_support.switchGray')
    tryBuild()
    sys.stdout.flush()

def blackBrowser():
    global w
    print('MainWindow_support.whiteBrowser')
    filename = filedialog.askopenfilename(filetypes=[('任何图片', '.*')])
    if filename:
        w.eblackImg.delete(0, END)
        w.eblackImg.insert(0, filename)
    sys.stdout.flush()

def whiteBrowser():
    global w
    print('MainWindow_support.whiteBrowser')
    filename = filedialog.askopenfilename(filetypes=[('任何图片', '.*')])
    if filename:
        w.ewhiteImg.delete(0, END)
        w.ewhiteImg.insert(0, filename)
    sys.stdout.flush()

def outputBrowser():
    global w
    print('MainWindow_support.outputBrowser')
    filename = filedialog.asksaveasfilename(filetypes=[('png图片', '.png')])
    if filename:
        w.eoutputImg.delete(0, END)
        w.eoutputImg.insert(0, filename)
    sys.stdout.flush()

def startBuild():
    global w, outputImg
    print('MainWindow_support.startBuild')

    saveOptions()

    tryBuild(False).save(outputImg.get(), 'PNG')

    messagebox.showinfo(title='提示', message='发车成功!')

    sys.stdout.flush()

def tryBuild(justATry=True):
    global w, whiteLight, blackLight, whiteImg, blackImg, whiteColor,\
        blackColor, blackScale, whiteScale, enableChess, colorfulCar

    print('MainWindow_support.tryBuild')

    _whiteImg = Image.open(whiteImg.get())
    _blackImg = Image.open(blackImg.get())

    _enableChess = enableChess.get()

    # 调整大小
    _whiteScale = whiteScale.get()
    _blackScale = blackScale.get()
    _whiteImg = _whiteImg.resize((round(x * _whiteScale) for x in _whiteImg.size), Image.ANTIALIAS)
    _blackImg = _blackImg.resize((round(x * _blackScale) for x in _blackImg.size), Image.ANTIALIAS)

    # 预览模式下, 先进行自定义比例的调整, 再以大的图像为标准进行等比例缩小
    if justATry:
        size = (w.showWhite.winfo_width(), w.showWhite.winfo_height())
        _whiteScale = min([size[i] / _whiteImg.size[i] for i in range(2)])
        _blackScale = min([size[i] / _blackImg.size[i] for i in range(2)])
        _sacle = min(_whiteScale, _blackScale)
        _whiteImg = _whiteImg.resize((round(x * _sacle) for x in _whiteImg.size), Image.ANTIALIAS)
        _blackImg = _blackImg.resize((round(x * _sacle) for x in _blackImg.size), Image.ANTIALIAS)

    if not colorfulCar.get():
        output = MTCore.grayCar(_whiteImg, _blackImg, whiteLight.get(), blackLight.get(), _enableChess)
    else:
        output = MTCore.colorfulCar(_whiteImg, _blackImg, whiteLight.get(), blackLight.get(), whiteColor.get(), blackColor.get(), _enableChess)

    if justATry:
        w._img = ImageTk.PhotoImage(output, height=size[1], width=size[0])
        w.showWhite.configure(image=w._img)
        w.showBlack.configure(image=w._img)

    sys.stdout.flush()
    return output

def saveOptions():

    option_list = ['whiteImg', 'blackImg', 'outputImg', 'whiteLight', 'blackLight', 'whiteColor', 'blackColor',
                   'whiteScale', 'blackScale', 'enableChess', 'colorfulCar']

    options = {option: globals()[option].get() for option in option_list}

    with open('options.json', 'w') as f:
        json.dump(options, f, indent=2)

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    root.resizable(False, False)

    try:
        remu = Image.open('remu.png')
        # TODO: 动态获取
        size = (340, 485)
        scale = min([size[i] / remu.size[i] for i in range(2)])
        remu = remu.resize((round(x * scale) for x in remu.size), Image.ANTIALIAS)
        w._img = ImageTk.PhotoImage(remu)
        w.showWhite.configure(image=w._img)
        w.showBlack.configure(image=w._img)

    except FileNotFoundError:
        pass

    # 居中
    # TODO: 动态获取
    width = 807
    height = 719
    scrWidth, scrHeight = (root.winfo_screenwidth(), root.winfo_screenheight())
    tmp = '{}x{}+{}+{}'.format(width, height, (scrWidth - width) // 2, (scrHeight - height) // 2)
    root.geometry(tmp)

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import MainWindow
    MainWindow.vp_start_gui()








