#############################################################################
# Generated by PAGE version 4.10
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_3_0 $base.fra38
    set site_3_0 $base.fra41
    set site_3_0 $base.fra67
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m38" -background {#d9d9d9} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 807x719+381+180
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 9999 9999
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "MirageTankGoGUI"
    frame $top.fra38 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 515 \
        -highlightcolor black -width 775 
    vTcl:DefineAlias "$top.fra38" "Frame1" vTcl:WidgetProc "$top" 1
    set site_3_0 $top.fra38
    label $site_3_0.lab39 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -foreground {#000000} -highlightcolor black \
        -text 白底效果 
    vTcl:DefineAlias "$site_3_0.lab39" "showWhite" vTcl:WidgetProc "$top" 1
    label $site_3_0.lab40 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#000000} -foreground {#ffffff} -highlightcolor black \
        -text 黑底效果 
    vTcl:DefineAlias "$site_3_0.lab40" "showBlack" vTcl:WidgetProc "$top" 1
    place $site_3_0.lab39 \
        -in $site_3_0 -x 20 -y 10 -width 340 -height 485 -anchor nw \
        -bordermode inside 
    place $site_3_0.lab40 \
        -in $site_3_0 -x 410 -y 10 -width 340 -height 485 -anchor nw \
        -bordermode inside 
    frame $top.fra41 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 175 \
        -highlightcolor black -width 375 
    vTcl:DefineAlias "$top.fra41" "Frame2" vTcl:WidgetProc "$top" 1
    set site_3_0 $top.fra41
    checkbutton $site_3_0.che42 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -command switchGray -foreground {#000000} \
        -highlightcolor black -justify left -text 启用棋盘格 -variable enableChess 
    vTcl:DefineAlias "$site_3_0.che42" "cenableChess" vTcl:WidgetProc "$top" 1
    checkbutton $site_3_0.che43 \
        -background {#d9d9d9} -command switchColor -foreground {#000000} \
        -justify left -text 发彩色车 -variable colorfulCar 
    vTcl:DefineAlias "$site_3_0.che43" "ccolorfulCar" vTcl:WidgetProc "$top" 1
    label $site_3_0.lab44 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text 白底色彩: 
    vTcl:DefineAlias "$site_3_0.lab44" "Label11" vTcl:WidgetProc "$top" 1
    label $site_3_0.lab45 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text 黑底色彩: 
    vTcl:DefineAlias "$site_3_0.lab45" "Label12" vTcl:WidgetProc "$top" 1
    spinbox $site_3_0.spi46 \
        -background white -foreground black -increment 0.01 -justify right \
        -textvariable whiteColor -to 1.0 
    vTcl:DefineAlias "$site_3_0.spi46" "swhiteColor" vTcl:WidgetProc "$top" 1
    spinbox $site_3_0.spi47 \
        -background white -foreground black -increment 0.01 -justify right \
        -textvariable blackColor -to 1.0 
    vTcl:DefineAlias "$site_3_0.spi47" "sblackColor" vTcl:WidgetProc "$top" 1
    label $site_3_0.lab48 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text 白底缩放: 
    vTcl:DefineAlias "$site_3_0.lab48" "Label13" vTcl:WidgetProc "$top" 1
    label $site_3_0.lab49 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text 黑底缩放: 
    vTcl:DefineAlias "$site_3_0.lab49" "Label8" vTcl:WidgetProc "$top" 1
    label $site_3_0.lab50 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text 白底亮度: 
    vTcl:DefineAlias "$site_3_0.lab50" "Label10" vTcl:WidgetProc "$top" 1
    label $site_3_0.lab51 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text 黑底亮度: 
    vTcl:DefineAlias "$site_3_0.lab51" "Label9" vTcl:WidgetProc "$top" 1
    spinbox $site_3_0.spi52 \
        -background white -foreground black -from 0.01 -increment 0.01 \
        -justify right -textvariable whiteScale -to 1.0 
    vTcl:DefineAlias "$site_3_0.spi52" "swhiteScale" vTcl:WidgetProc "$top" 1
    spinbox $site_3_0.spi53 \
        -activebackground {#f9f9f9} -background white -foreground black \
        -from 0.01 -increment 0.01 -justify right -textvariable blackScale \
        -to 1.0 
    vTcl:DefineAlias "$site_3_0.spi53" "sblackScale" vTcl:WidgetProc "$top" 1
    spinbox $site_3_0.spi54 \
        -activebackground {#f9f9f9} -background white -foreground black \
        -from 0.0 -increment 0.01 -justify right -textvariable whiteLight \
        -to 1.0 
    vTcl:DefineAlias "$site_3_0.spi54" "swhiteLight" vTcl:WidgetProc "$top" 1
    spinbox $site_3_0.spi55 \
        -activebackground {#f9f9f9} -background white -foreground black \
        -from 0.0 -increment 0.01 -justify right -textvariable blackLight \
        -to 1.0 
    vTcl:DefineAlias "$site_3_0.spi55" "sblackLight" vTcl:WidgetProc "$top" 1
    place $site_3_0.che42 \
        -in $site_3_0 -x 6 -y 12 -width 105 -height 26 -anchor nw \
        -bordermode ignore 
    place $site_3_0.che43 \
        -in $site_3_0 -x 6 -y 52 -width 90 -height 26 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab44 \
        -in $site_3_0 -x 10 -y 90 -width 68 -height 24 -anchor nw \
        -bordermode inside 
    place $site_3_0.lab45 \
        -in $site_3_0 -x 10 -y 130 -width 68 -height 24 -anchor nw \
        -bordermode inside 
    place $site_3_0.spi46 \
        -in $site_3_0 -x 90 -y 90 -width 76 -height 26 -anchor nw \
        -bordermode inside 
    place $site_3_0.spi47 \
        -in $site_3_0 -x 90 -y 130 -width 76 -height 26 -anchor nw \
        -bordermode inside 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 210 -y 10 -width 68 -height 24 -anchor nw \
        -bordermode inside 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 210 -y 50 -width 68 -height 24 -anchor nw \
        -bordermode inside 
    place $site_3_0.lab50 \
        -in $site_3_0 -x 210 -y 90 -width 68 -height 24 -anchor nw \
        -bordermode inside 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 210 -y 130 -width 68 -height 24 -anchor nw \
        -bordermode inside 
    place $site_3_0.spi52 \
        -in $site_3_0 -x 290 -y 10 -width 76 -height 26 -anchor nw \
        -bordermode inside 
    place $site_3_0.spi53 \
        -in $site_3_0 -x 290 -y 50 -width 76 -height 26 -anchor nw \
        -bordermode inside 
    place $site_3_0.spi54 \
        -in $site_3_0 -x 290 -y 90 -width 76 -height 26 -anchor nw \
        -bordermode inside 
    place $site_3_0.spi55 \
        -in $site_3_0 -x 290 -y 130 -width 76 -height 26 -anchor nw \
        -bordermode inside 
    frame $top.fra67 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 175 \
        -highlightcolor black -width 395 
    vTcl:DefineAlias "$top.fra67" "Frame3" vTcl:WidgetProc "$top" 1
    set site_3_0 $top.fra67
    label $site_3_0.lab57 \
        -background {#d9d9d9} -foreground {#000000} -text 白底图片: 
    vTcl:DefineAlias "$site_3_0.lab57" "Label1" vTcl:WidgetProc "$top" 1
    entry $site_3_0.ent60 \
        -background white -foreground {#000000} -textvariable whiteImg 
    vTcl:DefineAlias "$site_3_0.ent60" "ewhiteImg" vTcl:WidgetProc "$top" 1
    entry $site_3_0.ent61 \
        -background white -foreground {#000000} -textvariable blackImg 
    vTcl:DefineAlias "$site_3_0.ent61" "eblackImg" vTcl:WidgetProc "$top" 1
    entry $site_3_0.ent62 \
        -background white -foreground {#000000} -textvariable outputImg 
    vTcl:DefineAlias "$site_3_0.ent62" "eoutputImg" vTcl:WidgetProc "$top" 1
    button $site_3_0.but63 \
        -background {#d9d9d9} -command whiteBrowser -foreground {#000000} \
        -text 浏览.. 
    vTcl:DefineAlias "$site_3_0.but63" "bwhiteBrowse" vTcl:WidgetProc "$top" 1
    button $site_3_0.but64 \
        -background {#d9d9d9} -command blackBrowser -foreground {#000000} \
        -text 浏览.. 
    vTcl:DefineAlias "$site_3_0.but64" "bblackBrowse" vTcl:WidgetProc "$top" 1
    button $site_3_0.but68 \
        -background {#d9d9d9} -command outputBrowser -foreground {#000000} \
        -text 浏览.. 
    vTcl:DefineAlias "$site_3_0.but68" "boutputBrowse" vTcl:WidgetProc "$top" 1
    button $site_3_0.but69 \
        -background {#d9d9d9} -command tryBuild -foreground {#000000} \
        -text 试驾 
    vTcl:DefineAlias "$site_3_0.but69" "btryBuild" vTcl:WidgetProc "$top" 1
    button $site_3_0.but70 \
        -background {#d9d9d9} -command startBuild -foreground {#000000} \
        -text 开始发车! 
    vTcl:DefineAlias "$site_3_0.but70" "bstartBuild" vTcl:WidgetProc "$top" 1
    label $site_3_0.lab71 \
        -background {#d9d9d9} -foreground {#000000} -text 黑底图片: 
    vTcl:DefineAlias "$site_3_0.lab71" "Label2" vTcl:WidgetProc "$top" 1
    label $site_3_0.lab72 \
        -background {#d9d9d9} -foreground {#000000} -text 输出图片: 
    vTcl:DefineAlias "$site_3_0.lab72" "Label3" vTcl:WidgetProc "$top" 1
    place $site_3_0.lab57 \
        -in $site_3_0 -x 22 -y 12 -width 68 -height 24 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent60 \
        -in $site_3_0 -x 100 -y 10 -width 206 -height 26 -anchor nw \
        -bordermode inside 
    place $site_3_0.ent61 \
        -in $site_3_0 -x 100 -y 40 -width 206 -height 26 -anchor nw \
        -bordermode inside 
    place $site_3_0.ent62 \
        -in $site_3_0 -x 100 -y 70 -width 206 -height 26 -anchor nw \
        -bordermode inside 
    place $site_3_0.but63 \
        -in $site_3_0 -x 310 -y 10 -width 72 -height 26 -anchor nw \
        -bordermode inside 
    place $site_3_0.but64 \
        -in $site_3_0 -x 310 -y 40 -width 72 -height 26 -anchor nw \
        -bordermode inside 
    place $site_3_0.but68 \
        -in $site_3_0 -x 310 -y 70 -width 72 -height 26 -anchor nw \
        -bordermode inside 
    place $site_3_0.but69 \
        -in $site_3_0 -x 20 -y 110 -width 132 -height 42 -anchor nw \
        -bordermode inside 
    place $site_3_0.but70 \
        -in $site_3_0 -x 240 -y 110 -width 132 -height 42 -anchor nw \
        -bordermode inside 
    place $site_3_0.lab71 \
        -in $site_3_0 -x 20 -y 40 -width 68 -height 24 -anchor nw \
        -bordermode inside 
    place $site_3_0.lab72 \
        -in $site_3_0 -x 20 -y 70 -width 68 -height 24 -anchor nw \
        -bordermode inside 
    menu $top.m38 \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    $top.m38 add command \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -command {#mabout} -font TkMenuFont \
        -foreground {#000000} -label 关于 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra38 \
        -in $top -x 20 -y 190 -width 775 -relwidth 0 -height 515 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra41 \
        -in $top -x 420 -y 10 -width 375 -relwidth 0 -height 175 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra67 \
        -in $top -x 20 -y 10 -width 395 -relwidth 0 -height 175 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

  set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
Window show .
Window show .top37 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

